Simplified sample code for G-code optimization written by MATLAB.
Copyright 2023 Kyoto University
Author: Shuntaro Yamato

Main1_GenerateGcode
-> Corresponding G-code txt file and Summary data(.mat) are generated from the scheduled feedrate data

Main2_GcodeOptimization
-> Import Summary data generated by "Main1", and then output optimized G-code txt file